services:
  exam-eye:
    build:
      context: .
      dockerfile: Dockerfile
    image: exam-eye-ai:latest
    container_name: exam-eye-ai
    runtime: nvidia
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./logs:/app/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/video0:/dev/video0
    stdin_open: true
    tty: true
    restart: unless-stopped
